# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#
# TODO(franklinn): Stop tagging java/javac images once usage has dropped off.

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--no-cache'
  - '--build-arg=BASE_IMAGE=openjdk:10'
  - '--build-arg=DOCKER_VERSION=18.06.1~ce~3-0~debian'
  - '--tag=gcr.io/$PROJECT_ID/javac:10'
  - '--tag=gcr.io/$PROJECT_ID/java/javac:10'
  - '.'
  waitFor: ['-']
  id: 'BUILD_JDK_10'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--no-cache'
  - '--build-arg=BASE_IMAGE=openjdk:11'
  - '--build-arg=DOCKER_VERSION=18.06.1~ce~3-0~debian'
  - '--tag=gcr.io/$PROJECT_ID/javac:11'
  - '--tag=gcr.io/$PROJECT_ID/java/javac:11'
  - '.'
  waitFor: ['-']
  id: 'BUILD_JDK_11'

# Test that javac and docker are installed, for all built images, and that apt-get update will work
# in child images

- name: 'gcr.io/$PROJECT_ID/javac:10'
  args: ['-version']
  waitFor: ['BUILD_JDK_10']
- name: 'gcr.io/$PROJECT_ID/javac:11'
  args: ['-version']
  waitFor: ['BUILD_JDK_11']

images:
- 'gcr.io/$PROJECT_ID/javac:10'
- 'gcr.io/$PROJECT_ID/java/javac:10'
- 'gcr.io/$PROJECT_ID/javac:11'
- 'gcr.io/$PROJECT_ID/java/javac:11'
